# https://github.com/apache/incubator-opendal/blob/main/.github/actions/setup/action.yaml
# https://github.com/mozilla/sccache/blob/main/.github/actions/rust-toolchain/action.yml

name: Setup Rust Builder
description: 'Prepare Rust Build Environment'
inputs:
  toolchain:
    description: |
      Rust toolchain name.
      See https://rust-lang.github.io/rustup/concepts/toolchains.html#toolchain-specification
    required: false
  cache-key:
    description: 'the rust cache key suffix'
    required: false
    default: ''
  components:
    description: Space-separated list of components to be additionally installed for a new toolchain
    required: false

runs:
  using: "composite"
  steps:
    - name: Cache Cargo
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}${{ inputs.cache-key }}
        restore-keys: |
          ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          ${{ runner.os }}-cargo
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.3

    - name: Setup rust toolchain
      shell: bash
      run: |
        set -x
        # Update rust to latest stable
        rustup override set ${{ inputs.toolchain || 'stable' }}
        ${{ inputs.components && format('rustup component add {0}', inputs.components) }}
    - name: Setup Env
      shell: bash
      run: |
        # Disable full debug symbol generation to speed up CI build and keep memory down
        # "1" means line tables only, which is useful for panic tracebacks.
        echo "RUSTFLAGS=-C debuginfo=1" >> $GITHUB_ENV
        # Enable backtraces
        echo "RUST_BACKTRACE=1" >> $GITHUB_ENV
        # Enable logging
        echo "RUST_LOG=debug" >> $GITHUB_ENV
        # Enable sparse index
        echo "CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse" >> $GITHUB_ENV
